{{- if .Values.langinfra.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langinfra.fullname" . }}-frontend
  labels:
    app: {{ template "langinfra.name" . }}
    chart: {{ template "langinfra.chart" . }}
    release: {{ .Release.Name }}
    langinfra-scope: "frontend"
spec:
  replicas: {{ .Values.langinfra.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "langinfra.name" . }}
      chart: {{ template "langinfra.chart" . }}
      release: {{ .Release.Name }}
      langinfra-scope: "frontend"
  template:
    metadata:
      {{- with .Values.langinfra.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "langinfra.name" . }}
        chart: {{ template "langinfra.chart" . }}
        release: {{ .Release.Name }}
        langinfra-scope: "frontend"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "langinfra.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.langinfra.frontend.podSecurityContext | nindent 8 }}
      volumes:
        {{- if .Values.secretProvider.enabled }}
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{- .Values.secretProvider.name }}"
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.langinfra.securityContext | nindent 12 }}
          image: "{{ .Values.langinfra.frontend.image.repository }}:{{ .Values.langinfra.frontend.image.tag | default .Values.langinfra.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.langinfra.frontend.image.pullPolicy | default .Values.langinfra.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.langinfra.frontend.service.port }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.secretProvider.enabled }}
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
            {{- end }}
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: {{ .Values.langinfra.frontend.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.langinfra.frontend.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.langinfra.frontend.probe.timeoutSeconds }}
            failureThreshold: {{ .Values.langinfra.frontend.probe.failureThreshold }}   
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: {{ .Values.langinfra.frontend.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.langinfra.frontend.probe.periodSeconds }}
            timeoutSeconds: {{ .Values.langinfra.frontend.probe.timeoutSeconds }}
            failureThreshold: {{ .Values.langinfra.frontend.probe.failureThreshold }}   
          env:
            - name: BACKEND_URL
              value: "http://{{ template "langinfra.fullname" . }}-backend.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.langinfra.backend.service.port }}"
            - name: FRONTEND_PORT
              value: "{{ .Values.langinfra.frontend.service.port }}"
          resources:
            {{- toYaml .Values.langinfra.frontend.resources | nindent 12 }}
      {{- with .Values.langinfra.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.langinfra.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.langinfra.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}